# CloudFormation Boilerplate
AWSTemplateFormatVersion: '2010-09-09'

# Tell CloudFormation to use the AWS Serverless Aplication Model extensions.
# AWS SAM Docs: http://docs.aws.amazon.com/lambda/latest/dg/deploying-lambda-apps.html#serverless_app
# SAM Specification: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # Create a DynamoDB Table in which we can save our favorite gauges.
  # Reference: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable
  FavoriteGauges:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: USGSSiteNumber
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SlackGaugesCommand:
    Type: AWS::Serverless::Function
    Properties:
      Handler: gauges.lambda_handler
      Runtime: python2.7
      CodeUri: ./tmp/lambda_deployment_package.zip
      Description: Handler for /gauges Slack command
      MemorySize: 128
      Timeout: 3 # Enforced by Slack
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: DecryptSlackToken
              Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource: '*'
            - Sid: DynamoDBUsage
              Effect: Allow
              Action:
                - 'dynamodb:Get*'
                - 'dynamodb:Describe*'
                - 'dynamodb:*Item'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
              Resource: 'arn:aws:dynamodb:*:*:table/river-gauges-app-*'
      Events:
        RiverGaugesApi:
          Type: Api
          Properties:
            Path: /gauges
            Method: ANY
      Environment:
        Variables:
          foo: bar
          favoriteGaugesTable: !Ref FavoriteGauges
          kmsEncryptedToken: AQICAHhdVLBYeYKe3sWfFhcr4BYYa3XgjiHyRIY476ypxjn0pQGjfuvTDJD1rhPaZLACtqvdAAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMh46Pe9g7mrAn3m2gAgEQgDPLB8zS2guRHQHi/eGtUuBqOwjRONEB7fBjXmdHa6j7YSBVuKm8slAkZaZ3fbukoxHazPE=
